### ISSUE TITLE
Support new API

### ISSUE THREAD

**Issue by Grovespaz** [narfunikita/Osrm.Client#1]
Hey, I just discovered this library and it has been working pretty great for me, so thanks!
I noticed that it didn't work on the latest version of OSRM (development branch), since ORM has switched to a new API format (See https://github.com/Project-OSRM/osrm-backend/wiki/New-Server-api)

Are you planning to support this new API?

**Comment by narfunikita** [comment]
Hi, thanks alot for informing about new OSRM API version.
I will add new API in the next month.

**Comment by Grovespaz** [comment]
Great news, thanks for the quick response too!
